[package]
name = "pbtui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
noodles-bam = "0.46.0"
noodles-core = "0.12.0"
